require("plugins")
require("core.options")
require("core.keymaps")
require("core.colorscheme")
require("plugin_config.mason")
require("plugin_config.lsp_config")
require("plugin_config.completions")
require("plugin_config.treesitter")
require("plugin_config.compilot")
require("plugin_config.autosaving")
require("plugin_config.autopair")
require("plugin_config.lualine")
require("plugin_config.debug")
--require("plugin_config.prettier")
vim.cmd('silent! set fileencoding=utf-8')
